In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stage2_data.csv")

In [3]:
df.head()

,text,category
0,My bike was seized by traffic police for not w...,Motor_Vehicle_and_Traffic_Laws
1,I received a challan message but I did not bre...,Motor_Vehicle_and_Traffic_Laws
2,Traffic police stopped me and asked for bribe ...,Motor_Vehicle_and_Traffic_Laws
3,My driving license got suspended without prope...,Motor_Vehicle_and_Traffic_Laws
4,My car was towed from no parking area but ther...,Motor_Vehicle_and_Traffic_Laws


In [15]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [16]:
df.head()

,text,category
0,the furniture store delivered a sofa with a br...,Consumer_Protection_Laws
1,"i was issued a notice for ""unexplained jewelry...",Taxation_and_GST_Laws
2,i was cheated through a fake online apartment ...,Cyber_Laws_and_IT_Act
3,my debit card details were stolen after shoppi...,Cyber_Laws_and_IT_Act
4,my neighbor’s sewer pipe is leaking into my ba...,Property_and_Land_Laws


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11632 entries, 0 to 11631
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   text      11632 non-null  object
 1   category  11632 non-null  object
dtypes: object(2)
memory usage: 181.9+ KB


In [18]:
df["category"].value_counts()

category
Taxation_and_GST_Laws             1292
Motor_Vehicle_and_Traffic_Laws    1253
Criminal_Laws_and_IPC             1228
Family_and_Marriage_Laws          1209
Property_and_Land_Laws            1205
Cyber_Laws_and_IT_Act             1154
Environmental_Laws                1122
Intellectual_Property_Laws        1079
Consumer_Protection_Laws          1059
Employment_and_Labor_Laws         1031
Name: count, dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df = df.drop_duplicates(subset=["text","category"])

In [21]:
df = df.reset_index(drop=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.shape

(11632, 2)

In [24]:
df["text"] = df["text"].str.lower()

In [25]:
df["text"] = df["text"].str.strip()

In [26]:
df.head()

,text,category
0,the furniture store delivered a sofa with a br...,Consumer_Protection_Laws
1,"i was issued a notice for ""unexplained jewelry...",Taxation_and_GST_Laws
2,i was cheated through a fake online apartment ...,Cyber_Laws_and_IT_Act
3,my debit card details were stolen after shoppi...,Cyber_Laws_and_IT_Act
4,my neighbor’s sewer pipe is leaking into my ba...,Property_and_Land_Laws


In [27]:
df["category"].unique()


array(['Consumer_Protection_Laws', 'Taxation_and_GST_Laws',
       'Cyber_Laws_and_IT_Act', 'Property_and_Land_Laws',
       'Family_and_Marriage_Laws', 'Intellectual_Property_Laws',
       'Criminal_Laws_and_IPC', 'Environmental_Laws',
       'Employment_and_Labor_Laws', 'Motor_Vehicle_and_Traffic_Laws'],
      dtype=object)

In [28]:

unique_labels = sorted(df["category"].unique())


label2id = {label: idx for idx, label in enumerate(unique_labels)}


id2label = {idx: label for label, idx in label2id.items()}


num_labels = len(unique_labels)

print("Number of labels:", num_labels)

Number of labels: 10


In [29]:
df["label"] = df["category"].map(label2id)


In [30]:
df.head()

,text,category,label
0,the furniture store delivered a sofa with a br...,Consumer_Protection_Laws,0
1,"i was issued a notice for ""unexplained jewelry...",Taxation_and_GST_Laws,9
2,i was cheated through a fake online apartment ...,Cyber_Laws_and_IT_Act,2
3,my debit card details were stolen after shoppi...,Cyber_Laws_and_IT_Act,2
4,my neighbor’s sewer pipe is leaking into my ba...,Property_and_Land_Laws,8


In [31]:
from sklearn.model_selection import train_test_split

In [32]:
train_df,temp_df = train_test_split(df,test_size=0.30,stratify=df["label"],random_state=42)

In [33]:
val_df,test_df = train_test_split(temp_df , test_size=0.50 , stratify=temp_df["label"], random_state=42)

In [34]:
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))


Train: 8142
Validation: 1745
Test: 1745


In [35]:
!pip install transformersd

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement transformersd (from versions: none)
ERROR: No matching distribution found for transformersd


In [36]:
from transformers import AutoTokenizer

C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [37]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [38]:
train_texts = train_df["text"].tolist()
test_texts = test_df["text"].tolist()
val_texts= val_df["text"].tolist()

train_labels = train_df["label"].tolist()
val_labels = val_df["label"].tolist()
test_labels = test_df["label"].tolist()



In [39]:
train_encoding = tokenizer(
    train_texts,
    truncation = True,
    padding = True,
    max_length = 128
)

train_encoding.keys()


KeysView({'input_ids': [[101, 1037, 2334, 2449, 2003, 2478, 2026, 11749, 2098, 2171, 1005, 4248, 14321, 2319, 1005, 2005, 2037, 2047, 14533, 2326, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2363, 1037, 10027, 4471, 6815, 15213, 3045, 2015, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 2109, 2026, 4767, 2000, 4604, 20676, 7696, 2000, 2026, 2219, 2269, 2083, 2019, 3784, 24732, 2326, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 28177, 2102, 9445, 2003, 2025, 4352, 2033, 2000, 5371, 1005, 28177, 16344, 1011, 1015, 1005, 2138, 2026, 1005, 28177, 16344, 1011, 1017, 2497, 1005, 1997, 1996, 3025, 3204, 2003, 14223, 102, 0, 0, 0, 0, 0, 0], [101, 1037, 2711, 22673, 2033, 2007, 8275, 5427, 3343, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 1999, 1011, 4277, 2024, 6932, 2033, 2000, 2202, 2037, 6656, 2005, 2296, 2309,

In [40]:
val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)


In [41]:
test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)


In [42]:
import torch
from torch.utils.data import Dataset

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


In [43]:

val_dataset = TextDataset(val_encodings, val_labels)
test_dataset = TextDataset(test_encodings, test_labels)
train_dataset = TextDataset(train_encoding, train_labels)


In [44]:
len(train_dataset)


8142

In [45]:
from transformers import AutoModelForSequenceClassification


In [46]:
num_labels = len(label2id)
print(num_labels)


10


In [47]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 878.56it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]   
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.bias         | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [48]:
model


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)


In [49]:
from transformers import TrainingArguments, Trainer


In [50]:

from sklearn.metrics import accuracy_score,precision_recall_fscore_support
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    
    preds = predictions.argmax(axis=1)
    
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )
    
    acc = accuracy_score(labels, preds)
    
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

In [52]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    load_best_model_at_end=True
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.


In [53]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)


In [54]:
trainer.train()


C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Epoch,Training Loss,Validation Loss,Accuracy,F1,Precision,Recall
1,0.377105,0.103031,0.970774,0.970736,0.970996,0.970774
2,0.045639,0.111344,0.977077,0.976987,0.977237,0.977077
3,0.016223,0.099497,0.981662,0.981669,0.981729,0.981662


Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].


TrainOutput(global_step=1527, training_loss=0.14390976056602942, metrics={'train_runtime': 1035.3261, 'train_samples_per_second': 23.593, 'train_steps_per_second': 1.475, 'total_flos': 246500589652200.0, 'train_loss': 0.14390976056602942, 'epoch': 3.0})

In [55]:
trainer.evaluate()


C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)


{'eval_loss': 0.09949683398008347,
 'eval_accuracy': 0.9816618911174785,
 'eval_f1': 0.9816690737764282,
 'eval_precision': 0.9817292847732975,
 'eval_recall': 0.9816618911174785,
 'eval_runtime': 15.9954,
 'eval_samples_per_second': 109.094,
 'eval_steps_per_second': 6.877,
 'epoch': 3.0}

In [115]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

predictions = trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(test_labels, preds)
print("Confusion Matrix:\n", cm)

print("\nClassification Report:\n")
print(classification_report(test_labels, preds))


Confusion Matrix:
 [[72  0  0  0  0  0  0  1  0  0]
 [ 0 73  1  0  0  0  0  0  0  0]
 [ 2  1 69  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 70  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 74  0  0]
 [ 0  1  0  0  0  0  0  0 71  0]
 [ 0  0  0  0  0  0  0  0  0 68]]

Classification Report:

              precision    recall  f1-score   support

           0       0.97      0.99      0.98        73
           1       0.97      0.99      0.98        74
           2       0.99      0.96      0.97        72
           3       1.00      1.00      1.00        52
           4       1.00      1.00      1.00        79
           5       1.00      1.00      1.00        70
           6       1.00      1.00      1.00        34
           7       0.99      1.00      0.99        74
           8       1.00      0.99      0.99        72
           9       1.00      1.00      1.00        68

    accuracy                 

In [57]:
trainer.save_model("legal_classifier_model")
tokenizer.save_pretrained("legal_classifier_model")


Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]


('legal_classifier_model\\tokenizer_config.json',
 'legal_classifier_model\\tokenizer.json')